### ISSUE TITLE
Encoded lists only contain the first element (libSass 3.3)

### ISSUE THREAD

**Issue by p2media** [HugoGiraudel/SassyJSON#88]
This is not a bug in SassyJSON, rather than it's a bug in `libSass`.
I just want to inform you.

scss:
```scss
$map: (first, second, third, fourth);

body {
	content: call("_json-encode--list", $map);
	font-family: _json-encode--list($map);
}
```

CSS:
```css
body {
	content: '["first"]';
	font-family: '["first", "second", "third", "fourth"]'
}
```

Using:
```
node-sass	3.4.0-beta1	(Wrapper)	[JavaScript]
libsass  	3.3.0-beta2	(Sass Compiler)	[C/C++]
```
